name: Teleport
author: Elder Barbosa Romao
version: 2.1
main: Teleport
api-version: 1.21
commands:
  tpa:
    descrition: Teletransporta para os locais principais
  setHome:
    description: Salva as coordenadas
  deleteHome:
    description: Apaga o home
  createworld:
    description: Cria novo mundo
  deleteworld:
    description: Deleta o mundo
