name: Teleport
author: Elder Barbosa Romao
version: 1.0
main: Teleport
api-version: 1.15
commands:
  tpa:
    descrition: Teletransporta para os locais principais
  sethome:
    permission:
    description: Salva as coordenadas
  deleteHome:
    description: Apaga o home
