name: Teleport
author: Elder Barbosa Romao
version: 2.0
main: Teleport
api-version: 1.19
commands:
  tpa:
    descrition: Teletransporta para os locais principais
    permission: true
  sethome:
    permission:
    description: Salva as coordenadas
  deleteHome:
    description: Apaga o home
